name: first ci cd
on: 
  push:
    path: 
      - '!README.md'
      - '!docs/**'
      - '**.js'
      - '**.html'
    branches: 
      - 'master'
      - 'release/**'
      - '!dev/**'
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "today=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo hello world, today is $today